---
title: "gssurgo_processing_2"
author: "ML"
date: "2023-04-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Load packages, specify fxn for finding the mode, create a list of files ----

library(tidyverse)
library(sf)
library(fasterize)
library(raster)
library(tigris)
library(fuzzyjoin)
library(parallel)
library(dplyr)
library(readr)
#library(gdalUtils)

```

# the function 

```{r mode}
mode <- function(x, na.rm = TRUE) {
  if(na.rm){
    x = x[!is.na(x)]
  }
  
  ux <- na.omit(unique(x))
  return(ux[which.max(tabulate(match(x, ux)))])
}

```

# read CropScape data

```{r CropScape}
counties <- tigris::counties(year = 2022)
# load the corn frequency raster from CropScape - reports how many years between 
# 2008-2022 each pixel was used for maize production.
crop.freq <- brick('/home/shared/Kane_data/CropScape/crop_frequency_corn_2008-2022.tif')

```

# create list of filenames with gSSURGO polygon data

```{r soil}
all_counties_rds_list <- list.files("~/Documents/Kane_data/county_gssurgo_gdbs", full.names = T, pattern = ".rds")

# define function that takes individual county gSSURGO vector, converts to raster, 
# masks/resamples that raster by corn cells,
# then computes summary stats
soil.stats.gather <- function(i){

  # Set GEOID variable for function enviroment
  temp.GEOID <- unique(i$GEOID)
  
  # Set boundary object for the county
  #ibound <- spTransform(subset(counties,GEOID %in% temp.GEOID), CRSobj = crs(crop.freq))
  ibound <- st_transform(subset(counties,GEOID %in% temp.GEOID), st_crs(crop.freq))
  
  # Create reclassification matrix for converting crop frequency data into binary raster
  # binary for had 2+ years of corn data or did not. to identify pixels from any field in
  # which maize grown with relative consistency but not opportunistically 
  # while also eliminating non-crop areas of counties
  #rcl.m <- matrix(c(-Inf,2, NA,
  #                  2, Inf,1), 
  #                ncol=3, 
  #                byrow=TRUE)
  
  # ML: the original code has a bug; where the no corn cell value =255 is also considered as corn cells; this can corrected with the following reclassification matrix
  rcl.m <- matrix(c(-Inf,2, NA,
                    2, 254,1,
                    254,Inf,NA), 
                  ncol=3, 
                  byrow=TRUE)
  
  # Create mask object
  imask <-
    reclassify(projectRaster(mask(crop(crop.freq, y = ibound), ibound), res = 30, crs = crs(ibound)), rcl.m)
  
  # Convert dataframe to SF object
  i <- st_as_sf(i)
  
  # Create blank raster to rasterize sf to
  irast <- raster(imask)
  
  # ML: order needs to be a 'double' type, recode as numbers
  i <- i %>%
    mutate(order = dplyr::recode(order, 
                                           "Alfisol"= 1,
                                           "Entisols" = 2,
                                           "Histosols"=3,
                                           "Inceptisols"= 4,
                                           "Mollisols" = 5,
                                           "Spodosols"= 6,
                                           "Ultisols" = 7,
                                           "Vertisols" = 8,
                                           "Aridisols" = 9))
  
  # Convert the county-level data to a raster stack
  temp.raster <- raster::stack(fasterize(sf = i, raster = irast, field = "soc"),
                               fasterize(sf = i, raster = irast, field = "clay"),
                               fasterize(sf = i, raster = irast, field = "sand"),
                               fasterize(sf = i, raster = irast, field = "silt"),
                               fasterize(sf = i, raster = irast, field = "om"),
                               fasterize(sf = i, raster = irast, field = "awc"),
                               fasterize(sf = i, raster = irast, field = "aws"),
                               fasterize(sf = i, raster = irast, field = "fifteenbar"),
                               fasterize(sf = i, raster = irast, field = "cec"),
                               fasterize(sf = i, raster = irast, field = "ph"),
                               fasterize(sf = i, raster = irast, field = "droughty"),
                               fasterize(sf = i, raster = irast, field = "order")
                               )
  
  
  # Rename layers in the raster stack
  names(temp.raster) <-
    c("soc",
      "clay",
      "sand",
      "silt",
      "om",
      "awc",
      "aws",
      "fifteenbar",
      "cec",
      "ph",
      "droughty",
      "order")
  
  # Mask temp.raster to just the corn cells in the county
  temp.raster <- mask(temp.raster, mask = imask)
  
   # ML: we will mask the temp.raster to just the cells with <10% om
  om_mask <- reclassify(subset(temp.raster, 'om'), cbind(10, Inf, NA))
  temp.raster.om <- mask(temp.raster, mask = om_mask)
  
  # Summarize soils data for each county
  # ML: cellStats does not provide median on very large raster objects, use getValues+apply instead
  soil.stats.temp <- 
    cbind(temp.GEOID,
          as.data.frame(t(cellStats(subset(temp.raster, c(1:10)), 'mean'))) %>%
            rename_all(function(.) paste(.,"mean", sep = "_")),
          as.data.frame(t(apply(getValues(subset(temp.raster, c(1:10))),2,median,na.rm=TRUE))) %>%
            rename_all(function(.) paste(.,"median", sep = "_")),
          as.data.frame(t(cellStats(subset(temp.raster, c(11:12)), mode))) %>%
            rename_all(function(.) paste(.,"mode", sep = "_")),
          as.data.frame(t(cellStats(subset(temp.raster.om, c(1:10)), 'mean'))) %>%
            rename_all(function(.) paste(.,"filter_mean", sep = "_")),
          as.data.frame(t(apply(getValues(subset(temp.raster.om, c(1:10))),2,median,na.rm=TRUE))) %>%
            rename_all(function(.) paste(.,"filter_median", sep = "_")),
          as.data.frame(t(cellStats(subset(temp.raster.om, c(11:12)), mode))) %>%
            rename_all(function(.) paste(.,"filter_mode", sep = "_")))
  
  # Return
  return(soil.stats.temp)
  gc()
}

# run soil.stats.gather function on each list
gssurgo.soil.stats <- mclapply(mc.cores = 8, all_counties_rds_list, function(x){
    soil.stats.gather(i = read_rds(x))
  })

# Merge stats dfs and write to the hard drive
gssurgo.soil.stats <- plyr::ldply(gssurgo.soil.stats) %>%
  rename("GEOID" = temp.GEOID) %>%
  #rename_at(.vars = vars(2:23), .funs = function(x) paste("ssurgo", x, sep = "_")) %>%
  rename_at(.vars = vars(2:45), .funs = function(x) paste("ssurgo", x, sep = "_")) %>%
  mutate(ssurgo_order_mode = as.character(ssurgo_order_mode),
         ssurgo_order_mode = dplyr::recode(ssurgo_order_mode, 
                                           '1' = "Alfisol",
                                           '2' = "Entisols",
                                           '3' = "Histosols",
                                           '4' = "Inceptisols",
                                           '5' = "Mollisols",
                                           '6' = "Spodosols",
                                           '7' = "Ultisols",
                                           '8' = "Vertisols",
                                           '9' = "Aridisols"))
  

saveRDS(gssurgo.soil.stats, file = "~/Documents/Kane_data/gssurgo.soil.stats_filter_om10.rds")

```